apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        ports:
        image: 381443105140.dkr.ecr.eu-west-2.amazonaws.com/student-expense-tracker:v1
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-service
spec:
  selector:
    app: expense-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
